# Generated by Django 3.0.3 on 2020-09-19 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mprofile', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('perameter', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=5000, null=True)),
                ('totalPrice', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('delhiveryDate', models.DateField(null=True)),
                ('orderstatus', models.CharField(max_length=50, null=True)),
                ('paymentstatus', models.CharField(max_length=50, null=True)),
                ('txnId', models.CharField(max_length=500, null=True)),
                ('address', models.ForeignKey(db_column='address', null=True, on_delete=django.db.models.deletion.CASCADE, to='mprofile.Address')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='login.Loginmaster')),
            ],
        ),
    ]
