# Generated by Django 3.0.3 on 2020-09-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginUserName', models.CharField(max_length=100)),
                ('loginEmail', models.CharField(max_length=100)),
                ('loginMobileNo', models.CharField(blank=True, max_length=100, null=True)),
                ('loginPassword', models.CharField(max_length=50)),
                ('loginRole', models.CharField(max_length=50)),
                ('loginCreatedAt', models.DateField(auto_now_add=True)),
                ('loginStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OTPmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileOTP', models.IntegerField()),
                ('emailOTP', models.CharField(max_length=10)),
                ('login_Id', models.ForeignKey(db_column='login_Id', on_delete=django.db.models.deletion.CASCADE, to='login.Loginmaster')),
            ],
        ),
    ]
