# Generated by Django 3.0.3 on 2020-09-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='benner')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact', models.CharField(blank=True, max_length=13, null=True)),
                ('rank', models.IntegerField()),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default=0, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwhich', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=5000, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('promocode', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('totalsale', models.IntegerField(default=0)),
                ('coupon', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('categoryId', models.ForeignKey(db_column='categoryId', null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmodaz.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('wishProductId', models.ForeignKey(db_column='wishProductId', on_delete=django.db.models.deletion.CASCADE, to='shopmodaz.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('categoryId', models.ForeignKey(db_column='categoryId', null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmodaz.Category')),
                ('subcategoryId', models.ForeignKey(db_column='subcategoryId', null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmodaz.Subategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('productDescId', models.ForeignKey(db_column='productDescId', on_delete=django.db.models.deletion.CASCADE, to='shopmodaz.Product')),
            ],
        ),
    ]
